#!/bin/bash

# **********************
# ****** Cerbot ********
# **********************

# Run nginx docker for testing purposes
# docker run -it --name mynginx1 -v "${PWD}"/conf_files:/etc/nginx/conf.d/ -v "${PWD}"/custom_certs:/etc/ssl/custom_certs/ -p 443:443 -p 80:8080 -d --rm nginx

# Create certbot certificate
docker run -it --rm --name certbot -v "${PWD}/etc/letsencrypt:/etc/letsencrypt" -v "${PWD}/var/lib/letsencrypt:/var/lib/letsencrypt" -p 80:80 certbot/certbot certonly --standalone

# Renew the certificate
docker run -it --rm --name certbot -v "${PWD}/etc/letsencrypt:/etc/letsencrypt" -v "${PWD}/var/lib/letsencrypt:/var/lib/letsencrypt" -p 80:80 certbot/certbot renew

# ***********************
# ****** Jenkins ********
# ***********************

# Create Jenkins Keystore from PEM cert
# Combine certificate and private key to a single file
cat certs/fullchain.pem certs/privkey.pem >combined.pem
 
# Create PKCS12 certificate
openssl pkcs12 -export -in certs/combined.pem -out certs/cert.p12 -passout 'pass:CHANGE_IT_1'

# The tool to be executed in Java. You can also use an openjdk container for this purpose
# keytool -importkeystore -srckeystore cert.p12 -srcstorepass '1234' -srcstoretype pkcs12 -destkeystore jenkins_keystore.jks -deststorepass '123456'docker container run \
    -it --rm --name java_container \
    -v "${PWD}"/certs:/jenkins_jks openjdk \
    bash -c 'cd /jenkins_jks && keytool -importkeystore -srckeystore cert.p12 -srcstorepass "CHANGE_IT_1" -srcstoretype pkcs12 -destkeystore jenkins_keystore.jks -deststorepass "CHANGE_IT_2" '

# Create jenkins_home volume and copy Jenkins Keystore
docker volume create jenkins_home
sudo cp certs/jenkins_keystore.jks /var/lib/docker/volumes/jenkins_home/_data

# Start Jenkins
docker run --name jenkins -u root -d \
    -v jenkins_home:/var/jenkins_home \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v $(which docker):/usr/bin/docker \
    -p 443:8443 \
    jenkins/jenkins \
    --httpPort=-1 \
    --httpsPort=8443 \
    --httpsKeyStore=/var/jenkins_home/jenkins_keystore.jks \
    --httpsKeyStorePassword=CHANGE_IT_2